[package]
name = "rust_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
teloxide = { git = "https://github.com/teloxide/teloxide/", features = ["full"] } 
tokio = { version =  "1.8", features = ["rt-multi-thread", "macros"] }

